export const CollisionTag = Object.freeze({
  Default         : "default",
  Ship            : "ship",
  ShipBullet      : "ship-buttlet",
  Enemy           : "enemy",
  EnemyBullet     : "enemy-bullet",
  Bounding        : "bounding",
  Booster         : "booster",
  Vehicle         : "vehicle",
  Obstacle        : "obstacle",
  Star            : "star",
  Goal            : "goal",
  TurnLeftSign    : "turn-left-sign",
  TurnRightSign   : "turn-right-sign",
  TurnBackSign    : "turn-back-sign",
  NoneSign        : "none-sign",
  PavementBrick   : "pavement-brick",
});
